# Generated by Django 2.1.2 on 2018-10-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='unique_words',
            field=models.IntegerField(default=0),
        ),
    ]
